title: Richard Obeng
logo: https://media.licdn.com/dms/image/v2/D4E35AQHCiPkBUQnhdA/profile-framedphoto-shrink_200_200/B4EZmjpeb8KYAc-/0/1759387183127?e=1762401600&v=beta&t=V1VVd2X5nUIvnj9SZVMZuO5YYU1aiRHvmu7z0q3g7og
descriptiuon:
show_downloads: true
remote_theme: jekyll-theme-minimal
